<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCoSBEBb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCoSBEBb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCoSBEBb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCoSBEBb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCoSBEBb\App_KernelDevDebugContainer([
    'container.build_hash' => 'CoSBEBb',
    'container.build_id' => 'bc1f97f8',
    'container.build_time' => 1714871922,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCoSBEBb');
