<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxZH7VN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxZH7VN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxZH7VN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxZH7VN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxZH7VN\App_KernelDevDebugContainer([
    'container.build_hash' => 'WxZH7VN',
    'container.build_id' => '3a36132f',
    'container.build_time' => 1714921195,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxZH7VN');
